config/routes.rb
Ticketee::Application.routes.draw do

  
   root "projects#index"
   resources :projects do
    resources :tickets
  end
  resources :users
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
   
end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :name, presence: true
	has_many :tickets, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  private
  def require_signin!
    if current_user.nil?
      flash[:error] =
          "You need to sign in or sign up before continuing."
      redirect_to signin_url
    end
  end
  helper_method :require_signin!
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	//
before_action :set_project, only: [:show, :edit, :update, :destroy]
	 
  def index
  @projects = Project.all
  end
  def new
	@project = Project.new
  end
 
 //
  def show
    @project = Project.find(params[:id])
  end
  
  //
  def edit
	@project = Project.find(params[:id])
  end
	//
  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render "edit"
    end
  end
  
  //
   def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Project has been destroyed."
    redirect_to projects_path
  end
  
  
  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
		flash[:alert] = "Project has not been created."
		render "new"
	
# nothing, yet
    end
  end
  private
  def project_params
    params.require(:project).permit(:name, :description)
  end
  
  private
  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking for could not be found."
    redirect_to projects_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(*parts)
		unless parts.empty?
		  content_for :title do
			(parts << "Ticketee").join(" - ")
		  end
		end
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
        <%= yield(:title) %>
    <% else %>
        Ticketee
    <% end %>
  </title>
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
    <div class='flash' id='<%= key %>'>
      <%= value %>
    </div>
<% end %>

<%= yield %>

<nav>
  <ul>
    <li><%= link_to "Sign up", new_user_path %></li>
    <li><%= link_to "Sign in", signin_path %></li>
  </ul>
</nav>


</body>
</html>

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>
<h2>Projects</h2>
<ul>
  <% @projects.each do |project| %>
      <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h2>New Project</h2>
<%= render "form" %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>

<%= link_to "Edit Project", edit_project_path(@project) %>

<%= link_to "Delete Project",
            project_path(@project),
            method: :delete,
    data: { confirm:
    "Are you sure you want to delete this project?"
    } %>

<%= link_to "New Ticket", new_project_ticket_path(@project) %>

<ul id='tickets'>
  <% @project.tickets.each do |ticket| %>
      <li>
        #<%= ticket.id %> ­<%= link_to ticket.title, [@project, ticket] %>
      </li>
  <% end %>
</ul>